name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1.0.2
      with: 
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./stellar-dotnet-sdk-test/coverage.opencover.xml
    - name: Build Solution
      run: dotnet build ./stellar-dotnet-sdk.sln
    - name: Run Unit Tests
      run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:ExcludeByFile=\"../stellar-dotnet-sdk/chaos.nacl/**/*.cs\" -p:ExcludeByFile=\"../stellar-dotnet-sdk-xdr/generated/*.cs\" ./stellar-dotnet-sdk-test --test-adapter-path:. 
